### ISSUE TITLE
Feedback on your readme

### ISSUE THREAD

**Issue by RooyyDoe** [StefanGerrits2/Frontend-Applications#7]
- Als afbeelding heb je een flow van de user experience. Deze afbeeldingen zijn onhelder probeer dit aan te passen (Misschien ook groter?)
- Wiki is in het Nederlands en de readme is in het Engels. Kier hiervoor gewoon 1 taal waar jij jezelf prettig bij voelt.
- Maak een sub kopje aan met de opdracht die we hebben gekregen in deze course.
- Stap: 4 run server moet worden: 'npm run dev'
- Localhost:.... kan je gewoon de standaard host mee geven omdat die altijd hetzelfde blijft op deze manier raakt de gebruiker niet in de war.
- Laat misschien met een dropdown de API call zien. en vertel op welke manier je de specifieke data wil gaan krijgen.
- Als de readme heel lang gaat worden kan je een 'Table of content toevoegen' is een plugin voor in Visual Code
- Beschrijf features van je product/applicatie als deze er zijn.
- Misschien als je bepaalde bronnen hebt gebruikt kan je deze weergeven zodat mensen op een snelle manier kunnen zien waar je bepaalde features vandaan hebt.

**Comment by StefanGerrits2** [comment]
Bedankt voor je feedback Roy!

* Inderdaad verstandig om de flow duidelijker te maken van de app.
* Wiki houd ik liever in het Nederlands en readme in het Engels, ik voel me comfortabeler in het Nederlands. De wiki schrijf ik in het Engels zodat iedereen over de hele wereld mijn project kan begrijpen.
* Sub kopje zal ik over nadenken
* Localhost kan inderdaad altijd wel hetzelfde blijven
* Dropdown klinkt goed! Daar kan ik dus een query inzetten zodat je kan zien hoe ik data ophaal.
* Table of content vind ik zelf overbodig, maar kan ik zeker toevoegen als de Readme te lang wordt.
* Features beschrijven zal ik aan werken!
* Bronnen is ook inderdaad handig om toe te voegen.

Ik zal je feedback zo snel mogelijk verwerken :)

**Comment by StefanGerrits2** [comment]
Feedback is verwerkt! Nogmaals bedankt.
