### ISSUE TITLE
Feedback Wiki (Rubric)

### ISSUE THREAD

**Issue by RooyyDoe** [StefanGerrits2/Frontend-Applications#8]
- Misschien handig om een iets grotere uitleg te geven over het concept dat je nu hebt gekozen en hiervoor de schetsen wat meer/beter naar voor te laten komen.
- Geef een grotere uitleg over je query welke specifieke data je wilt ophalen en op welke manier je dit doet. Om hierdoor het proces te laten zien wat je hebt gemaakt.
- Ik mis de overige dagen dat je aan het project heb gewerkt in je logboek om het proces beter te beschrijven.

## extra puntjes
- Pak belangrijke punten in je proces waar jij extra op in wilt gaan en maak hiervoor een aparte file en verwerk dit dan in je logboek of iets dergelijke.
- Maak er een verhaal van.

**Comment by StefanGerrits2** [comment]
Bedankt voor je feedback, ik zal het verwerken.
